SET APP_ID='YOUR_MOSAIC_APP_ID';
SET APP_PUBLIC_KEY='YOUR_APP_PUBLIC_KEY'
SET APP_PRIVATE_KEY='YOUR_APP_PRIVATE_KEY'
SET APP_API_KEY='YOUR_API_KEY'

SET APP_URL='http://localhost:3010/?authorized';

node ./server.js
